services:
  mariadb:
    image: mariadb
    environment:
      - MARIADB_USER=userdb
      - MARIADB_PASSWORD=merdi
      - MARIADB_DATABASE=tp_serveur
      - MARIADB_ROOT_PASSWORD=root
    ports:
      - 3306:3306

  monapache:
    image: monapache
    ports:
      - "80:80"

  phpmyadmin:
    image: phpmyadmin
    environment:
      - PMA_HOST=mariadb
    ports:
      - 8080:80

  monubuntu:
    image: monubuntu
