services:
  mariadb:
    image: mariadb
    environment:
      - MARIADB_USER=userdb
      - MARIADB_PASSWORD=merdi
      - MARIADB_DATABASE=tp_serveur
      - MARIADB_ROOT_PASSWORD=root
    ports:
      - "3306:3306"

  monapache:
    build: ./monapache
    ports:
      - "81:80"
    depends_on:
      - mariadb

  phpmyadmin:
    image: phpmyadmin
    environment:
      - PMA_HOST=mariadb
    ports:
      - "8080:80"
    depends_on:
      - mariadb

  monubuntu:
    build: ./monubuntu
