services:
  web:
      build: .
      container_name: apache
      ports:
        - "80:80"
      volumes:
        - .:/var/www/html
      depends_on:
        - mariadb
      networks:
        - backend

  mariadb:
    image: mariadb:latest 
    container_name: mariadb
    environment:
      - MARIADB_USER=userdb
      - MARIADB_PASSWORD=merdi
      - MARIADB_DATABASE=tp_serveur
      - MARIADB_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    networks:
      - backend

  monapache:
    build: ./monapache
    ports:
      - "81:80"
    depends_on:
      - mariadb

  phpmyadmin: 
    image: phpmyadmin
    environment:
      - PMA_HOST=mariadb
    ports:
      - "8081:80"
    depends_on:
      - mariadb

  monubuntu:
    build: ./monubuntu

  networks:
    backend:
      driver: bridge